import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
// DO NOT EDIT THIS FILE
public class InventoryItemTest {
    @Test
    void checkNameSet() {
        InventoryItem i = new InventoryItem("Banana", 10);
        assertEquals("Banana", i.getName());
    }

    @Test
    void checkPriceSet() {
        InventoryItem i = new InventoryItem("Banana", 10);
        assertEquals(10, i.getPrice());
    }
}
