import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
// DO NOT EDIT THIS FILE
public class LineItemTest {
    @Test
    void checkItemSet() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5);
        assertEquals(b, l.getItem());
    }

    @Test
    void checkItemSetWithDiscount() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5, 0.2);
        assertEquals(b, l.getItem());
    }

    @Test
    void checkQuantitySet() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5);
        assertEquals(5, l.getQuantity());
    }

    @Test
    void checkQuantitySetWithDiscount() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5, 0.2);
        assertEquals(5, l.getQuantity());
    }

    @Test
    void checkDiscountDefault() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5);
        assertEquals(0, l.getDiscount(), 0.01);
    }

    @Test
    void checkDiscountSet() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5, 0.2);
        assertEquals(0.2, l.getDiscount(), 0.01);
    }

    @Test
    void checkTotalPrice() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5);
        assertEquals(50, l.getTotalPrice(), 0.01);
    }

    @Test
    void checkDiscountedTotalPrice() {
        InventoryItem b = new InventoryItem("Banana", 10);
        LineItem l = new LineItem(b, 5, 0.2);
        assertEquals(40, l.getTotalPrice(), 0.01);
    }
}
